version: '3.4'
services:
  config:
    build:
      context: config
      dockerfile: Dockerfile
    ports:
      - "8888:8888"

  discovery-server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  rabbit:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
        - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
        - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
        - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/

  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
     - "8081-8082:8081"
    depends_on:
      - discovery-server
      - config
      - mongo
      - rabbit

  api-getaway:
    build:
      context: getaway
      dockerfile: Dockerfile
    ports:
     - "9000:9000"
    depends_on:
      - client
      - config

 
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: planner
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/mongo:/data/db