version: '3.4'
services:
  config:
    build:
      context: config
      dockerfile: Dockerfile
    ports:
      - "8888:8888"

  discovery-server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  rabbit:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
        - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
        - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
        - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/

  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
     - "8081-8082:8081"
    depends_on:
      - discovery-server
      - config
      - mongo
      - rabbit

  api-gateway:
    build:
      context: getaway
      dockerfile: Dockerfile
    ports:
     - "9000:9000"
    depends_on:
      - client
      - config

 
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: planner
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/mongo:/data/db

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
      - "9080:9080"
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
  
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    hostname: zookeeper

  kafka:
    image: wurstmeister/kafka
    command: [start-kafka.sh]
    ports:
      - "9092:9092"
    hostname: kafka
    environment:
      KAFKA_CREATE_TOPICS: "create.entity:3:1,update.entity:3:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
    depends_on:
      - "zookeeper"
   