
global:
    scrape_interval:     15s # By default, scrape targets every 15 seconds.
  
    # Attach these labels to any time series or alerts when communicating with
    # external systems (federation, remote storage, Alertmanager).
    external_labels:
      monitor: 'resilience4j-monitor'
  

scrape_configs:
    - job_name: 'prometheus'
  
      # Override the global default and scrape targets from this job every 5 seconds.
      scrape_interval: 5s

      static_configs:
        - targets: ['prometheus:9090']
  
    - job_name: 'resilience4j-spring-boot2-demo'
  
      # Override the global default and scrape targets from this job every 5 seconds.
      scrape_interval: 5s
  
      metrics_path: /actuator/prometheus
  
      static_configs:
        - targets: ['api-gateway:9000']
  